/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsBoolean,
  ValidateNested,
  IsDate,
} from "class-validator";
import { PlanWhereUniqueInput } from "../../plan/base/PlanWhereUniqueInput";
import { Type } from "class-transformer";
import { UsageCreateNestedManyWithoutProjectsInput } from "./UsageCreateNestedManyWithoutProjectsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ProjectCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  appwriteProjectId?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PlanWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PlanWhereUniqueInput)
  @IsOptional()
  @Field(() => PlanWhereUniqueInput, {
    nullable: true,
  })
  plan?: PlanWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  suspendedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => UsageCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => UsageCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => UsageCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  usages?: UsageCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ProjectCreateInput as ProjectCreateInput };
