/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { BillingAccount } from "./BillingAccount";
import { BillingAccountCountArgs } from "./BillingAccountCountArgs";
import { BillingAccountFindManyArgs } from "./BillingAccountFindManyArgs";
import { BillingAccountFindUniqueArgs } from "./BillingAccountFindUniqueArgs";
import { CreateBillingAccountArgs } from "./CreateBillingAccountArgs";
import { UpdateBillingAccountArgs } from "./UpdateBillingAccountArgs";
import { DeleteBillingAccountArgs } from "./DeleteBillingAccountArgs";
import { InvoiceFindManyArgs } from "../../invoice/base/InvoiceFindManyArgs";
import { Invoice } from "../../invoice/base/Invoice";
import { User } from "../../user/base/User";
import { BillingAccountService } from "../billingAccount.service";
@graphql.Resolver(() => BillingAccount)
export class BillingAccountResolverBase {
  constructor(protected readonly service: BillingAccountService) {}

  async _billingAccountsMeta(
    @graphql.Args() args: BillingAccountCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [BillingAccount])
  async billingAccounts(
    @graphql.Args() args: BillingAccountFindManyArgs
  ): Promise<BillingAccount[]> {
    return this.service.billingAccounts(args);
  }

  @graphql.Query(() => BillingAccount, { nullable: true })
  async billingAccount(
    @graphql.Args() args: BillingAccountFindUniqueArgs
  ): Promise<BillingAccount | null> {
    const result = await this.service.billingAccount(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => BillingAccount)
  async createBillingAccount(
    @graphql.Args() args: CreateBillingAccountArgs
  ): Promise<BillingAccount> {
    return await this.service.createBillingAccount({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => BillingAccount)
  async updateBillingAccount(
    @graphql.Args() args: UpdateBillingAccountArgs
  ): Promise<BillingAccount | null> {
    try {
      return await this.service.updateBillingAccount({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => BillingAccount)
  async deleteBillingAccount(
    @graphql.Args() args: DeleteBillingAccountArgs
  ): Promise<BillingAccount | null> {
    try {
      return await this.service.deleteBillingAccount(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Invoice], { name: "invoices" })
  async findInvoices(
    @graphql.Parent() parent: BillingAccount,
    @graphql.Args() args: InvoiceFindManyArgs
  ): Promise<Invoice[]> {
    const results = await this.service.findInvoices(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(
    @graphql.Parent() parent: BillingAccount
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
