/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BillingAccountService } from "../billingAccount.service";
import { BillingAccountCreateInput } from "./BillingAccountCreateInput";
import { BillingAccount } from "./BillingAccount";
import { BillingAccountFindManyArgs } from "./BillingAccountFindManyArgs";
import { BillingAccountWhereUniqueInput } from "./BillingAccountWhereUniqueInput";
import { BillingAccountUpdateInput } from "./BillingAccountUpdateInput";
import { InvoiceFindManyArgs } from "../../invoice/base/InvoiceFindManyArgs";
import { Invoice } from "../../invoice/base/Invoice";
import { InvoiceWhereUniqueInput } from "../../invoice/base/InvoiceWhereUniqueInput";

export class BillingAccountControllerBase {
  constructor(protected readonly service: BillingAccountService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BillingAccount })
  async createBillingAccount(
    @common.Body() data: BillingAccountCreateInput
  ): Promise<BillingAccount> {
    return await this.service.createBillingAccount({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        currentPeriodEnd: true,
        id: true,
        isActive: true,
        stripeCustomerId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [BillingAccount] })
  @ApiNestedQuery(BillingAccountFindManyArgs)
  async billingAccounts(
    @common.Req() request: Request
  ): Promise<BillingAccount[]> {
    const args = plainToClass(BillingAccountFindManyArgs, request.query);
    return this.service.billingAccounts({
      ...args,
      select: {
        createdAt: true,
        currentPeriodEnd: true,
        id: true,
        isActive: true,
        stripeCustomerId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BillingAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async billingAccount(
    @common.Param() params: BillingAccountWhereUniqueInput
  ): Promise<BillingAccount | null> {
    const result = await this.service.billingAccount({
      where: params,
      select: {
        createdAt: true,
        currentPeriodEnd: true,
        id: true,
        isActive: true,
        stripeCustomerId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BillingAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBillingAccount(
    @common.Param() params: BillingAccountWhereUniqueInput,
    @common.Body() data: BillingAccountUpdateInput
  ): Promise<BillingAccount | null> {
    try {
      return await this.service.updateBillingAccount({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          currentPeriodEnd: true,
          id: true,
          isActive: true,
          stripeCustomerId: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BillingAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBillingAccount(
    @common.Param() params: BillingAccountWhereUniqueInput
  ): Promise<BillingAccount | null> {
    try {
      return await this.service.deleteBillingAccount({
        where: params,
        select: {
          createdAt: true,
          currentPeriodEnd: true,
          id: true,
          isActive: true,
          stripeCustomerId: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/invoices")
  @ApiNestedQuery(InvoiceFindManyArgs)
  async findInvoices(
    @common.Req() request: Request,
    @common.Param() params: BillingAccountWhereUniqueInput
  ): Promise<Invoice[]> {
    const query = plainToClass(InvoiceFindManyArgs, request.query);
    const results = await this.service.findInvoices(params.id, {
      ...query,
      select: {
        amount: true,

        billingAccount: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        issuedAt: true,
        paidAt: true,
        status: true,
        stripeInvoiceId: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/invoices")
  async connectInvoices(
    @common.Param() params: BillingAccountWhereUniqueInput,
    @common.Body() body: InvoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoices: {
        connect: body,
      },
    };
    await this.service.updateBillingAccount({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/invoices")
  async updateInvoices(
    @common.Param() params: BillingAccountWhereUniqueInput,
    @common.Body() body: InvoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoices: {
        set: body,
      },
    };
    await this.service.updateBillingAccount({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/invoices")
  async disconnectInvoices(
    @common.Param() params: BillingAccountWhereUniqueInput,
    @common.Body() body: InvoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoices: {
        disconnect: body,
      },
    };
    await this.service.updateBillingAccount({
      where: params,
      data,
      select: { id: true },
    });
  }
}
