/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Usage } from "./Usage";
import { UsageCountArgs } from "./UsageCountArgs";
import { UsageFindManyArgs } from "./UsageFindManyArgs";
import { UsageFindUniqueArgs } from "./UsageFindUniqueArgs";
import { CreateUsageArgs } from "./CreateUsageArgs";
import { UpdateUsageArgs } from "./UpdateUsageArgs";
import { DeleteUsageArgs } from "./DeleteUsageArgs";
import { Project } from "../../project/base/Project";
import { UsageService } from "../usage.service";
@graphql.Resolver(() => Usage)
export class UsageResolverBase {
  constructor(protected readonly service: UsageService) {}

  async _usagesMeta(
    @graphql.Args() args: UsageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Usage])
  async usages(@graphql.Args() args: UsageFindManyArgs): Promise<Usage[]> {
    return this.service.usages(args);
  }

  @graphql.Query(() => Usage, { nullable: true })
  async usage(
    @graphql.Args() args: UsageFindUniqueArgs
  ): Promise<Usage | null> {
    const result = await this.service.usage(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Usage)
  async createUsage(@graphql.Args() args: CreateUsageArgs): Promise<Usage> {
    return await this.service.createUsage({
      ...args,
      data: {
        ...args.data,

        project: args.data.project
          ? {
              connect: args.data.project,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Usage)
  async updateUsage(
    @graphql.Args() args: UpdateUsageArgs
  ): Promise<Usage | null> {
    try {
      return await this.service.updateUsage({
        ...args,
        data: {
          ...args.data,

          project: args.data.project
            ? {
                connect: args.data.project,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Usage)
  async deleteUsage(
    @graphql.Args() args: DeleteUsageArgs
  ): Promise<Usage | null> {
    try {
      return await this.service.deleteUsage(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Project, {
    nullable: true,
    name: "project",
  })
  async getProject(@graphql.Parent() parent: Usage): Promise<Project | null> {
    const result = await this.service.getProject(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
