/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { StripeWebhookEvent } from "./StripeWebhookEvent";
import { StripeWebhookEventCountArgs } from "./StripeWebhookEventCountArgs";
import { StripeWebhookEventFindManyArgs } from "./StripeWebhookEventFindManyArgs";
import { StripeWebhookEventFindUniqueArgs } from "./StripeWebhookEventFindUniqueArgs";
import { CreateStripeWebhookEventArgs } from "./CreateStripeWebhookEventArgs";
import { UpdateStripeWebhookEventArgs } from "./UpdateStripeWebhookEventArgs";
import { DeleteStripeWebhookEventArgs } from "./DeleteStripeWebhookEventArgs";
import { StripeWebhookEventService } from "../stripeWebhookEvent.service";
@graphql.Resolver(() => StripeWebhookEvent)
export class StripeWebhookEventResolverBase {
  constructor(protected readonly service: StripeWebhookEventService) {}

  async _stripeWebhookEventsMeta(
    @graphql.Args() args: StripeWebhookEventCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [StripeWebhookEvent])
  async stripeWebhookEvents(
    @graphql.Args() args: StripeWebhookEventFindManyArgs
  ): Promise<StripeWebhookEvent[]> {
    return this.service.stripeWebhookEvents(args);
  }

  @graphql.Query(() => StripeWebhookEvent, { nullable: true })
  async stripeWebhookEvent(
    @graphql.Args() args: StripeWebhookEventFindUniqueArgs
  ): Promise<StripeWebhookEvent | null> {
    const result = await this.service.stripeWebhookEvent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StripeWebhookEvent)
  async createStripeWebhookEvent(
    @graphql.Args() args: CreateStripeWebhookEventArgs
  ): Promise<StripeWebhookEvent> {
    return await this.service.createStripeWebhookEvent({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => StripeWebhookEvent)
  async updateStripeWebhookEvent(
    @graphql.Args() args: UpdateStripeWebhookEventArgs
  ): Promise<StripeWebhookEvent | null> {
    try {
      return await this.service.updateStripeWebhookEvent({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => StripeWebhookEvent)
  async deleteStripeWebhookEvent(
    @graphql.Args() args: DeleteStripeWebhookEventArgs
  ): Promise<StripeWebhookEvent | null> {
    try {
      return await this.service.deleteStripeWebhookEvent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
