/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  StripeWebhookEvent as PrismaStripeWebhookEvent,
} from "@prisma/client";

export class StripeWebhookEventServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.StripeWebhookEventCountArgs, "select">
  ): Promise<number> {
    return this.prisma.stripeWebhookEvent.count(args);
  }

  async stripeWebhookEvents(
    args: Prisma.StripeWebhookEventFindManyArgs
  ): Promise<PrismaStripeWebhookEvent[]> {
    return this.prisma.stripeWebhookEvent.findMany(args);
  }
  async stripeWebhookEvent(
    args: Prisma.StripeWebhookEventFindUniqueArgs
  ): Promise<PrismaStripeWebhookEvent | null> {
    return this.prisma.stripeWebhookEvent.findUnique(args);
  }
  async createStripeWebhookEvent(
    args: Prisma.StripeWebhookEventCreateArgs
  ): Promise<PrismaStripeWebhookEvent> {
    return this.prisma.stripeWebhookEvent.create(args);
  }
  async updateStripeWebhookEvent(
    args: Prisma.StripeWebhookEventUpdateArgs
  ): Promise<PrismaStripeWebhookEvent> {
    return this.prisma.stripeWebhookEvent.update(args);
  }
  async deleteStripeWebhookEvent(
    args: Prisma.StripeWebhookEventDeleteArgs
  ): Promise<PrismaStripeWebhookEvent> {
    return this.prisma.stripeWebhookEvent.delete(args);
  }
}
