/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StripeWebhookEventService } from "../stripeWebhookEvent.service";
import { StripeWebhookEventCreateInput } from "./StripeWebhookEventCreateInput";
import { StripeWebhookEvent } from "./StripeWebhookEvent";
import { StripeWebhookEventFindManyArgs } from "./StripeWebhookEventFindManyArgs";
import { StripeWebhookEventWhereUniqueInput } from "./StripeWebhookEventWhereUniqueInput";
import { StripeWebhookEventUpdateInput } from "./StripeWebhookEventUpdateInput";

export class StripeWebhookEventControllerBase {
  constructor(protected readonly service: StripeWebhookEventService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: StripeWebhookEvent })
  async createStripeWebhookEvent(
    @common.Body() data: StripeWebhookEventCreateInput
  ): Promise<StripeWebhookEvent> {
    return await this.service.createStripeWebhookEvent({
      data: data,
      select: {
        createdAt: true,
        eventId: true,
        id: true,
        payload: true,
        processed: true,
        receivedAt: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [StripeWebhookEvent] })
  @ApiNestedQuery(StripeWebhookEventFindManyArgs)
  async stripeWebhookEvents(
    @common.Req() request: Request
  ): Promise<StripeWebhookEvent[]> {
    const args = plainToClass(StripeWebhookEventFindManyArgs, request.query);
    return this.service.stripeWebhookEvents({
      ...args,
      select: {
        createdAt: true,
        eventId: true,
        id: true,
        payload: true,
        processed: true,
        receivedAt: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: StripeWebhookEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async stripeWebhookEvent(
    @common.Param() params: StripeWebhookEventWhereUniqueInput
  ): Promise<StripeWebhookEvent | null> {
    const result = await this.service.stripeWebhookEvent({
      where: params,
      select: {
        createdAt: true,
        eventId: true,
        id: true,
        payload: true,
        processed: true,
        receivedAt: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: StripeWebhookEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStripeWebhookEvent(
    @common.Param() params: StripeWebhookEventWhereUniqueInput,
    @common.Body() data: StripeWebhookEventUpdateInput
  ): Promise<StripeWebhookEvent | null> {
    try {
      return await this.service.updateStripeWebhookEvent({
        where: params,
        data: data,
        select: {
          createdAt: true,
          eventId: true,
          id: true,
          payload: true,
          processed: true,
          receivedAt: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: StripeWebhookEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStripeWebhookEvent(
    @common.Param() params: StripeWebhookEventWhereUniqueInput
  ): Promise<StripeWebhookEvent | null> {
    try {
      return await this.service.deleteStripeWebhookEvent({
        where: params,
        select: {
          createdAt: true,
          eventId: true,
          id: true,
          payload: true,
          processed: true,
          receivedAt: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
